[phases.setup]
nixPkgs = ["python311", "curl"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "chmod +x install-arduino-cli.sh",
  "./install-arduino-cli.sh"
]

[start]
cmd = "export PATH=$HOME/.local/bin:$PATH && python main.py"
