[build]
command = """
  pip install -r requirements.txt && \
  chmod +x install-arduino-cli.sh && \
  ./install-arduino-cli.sh
"""

[start]
command = "export PATH=$HOME/.local/bin:$PATH && python main.py"
